version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis:6379'
    volumes:
      - '.:/opt/app'
    ports:
      - '8000:8000'

  redis:
    image: 'redis:6'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'

